spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

#prefix
accounts:
  message: "Welcome to EazyBank accounts related local APIs QA 3.0"
  contactDetails:
    name: "Adnan Hashmi - QA Lead"
    email: "madnanhashmi@hotmail.com"
  onCallSupport:
    -(555) 555-0000
    -(555) 523-1111