spring:
  config:
    activate:
      on-profile: "qa"
      
build:
  version: "3.0"

cards:
  message: "Config Server - Welcome to EazyBank loans related default APIs "
  contactDetails:
    name: "Sandra Harald - @QA Owner"
    email: "sandra@eazybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721