build:
  version: "2.0"
#prefix
accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "Adnan Hashmi - Developer"
    email: "madnanhashmi@hotmail.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 523-1345